<?php
	$GLOBALS['lang'] = array(
		"Utilisateurs" => "Users",
		"lang_en" => "English",
		"lang_fr" => "French",
		"Recettes" => "Recipes",
		"Livraisons" => "Delivery",
		"Evennements" => "Events",
		"Ajouter_Chef" => "Add a Chef",
		"Images" => "Pictures",
		"liste_chefs" => "List of Chefs",
		"Nom" => "Last Name",
		"Prenom" => "First Name",
		"Date_naissance" => "Date of birth",
		"Nationalite" => "Nationality",
		"Image" => "Picture",
		"Modifier" => "UPDATE",
		"Supprimer" => "DELETE",
		"Ajouter" => "ADD",
		"Modifier_Chef" => "Chef Update",
		"Retourner" => "Go Back",
		"Msg" => "Chef deleted successfully",
		"RecherchePlaceholder" => "Name of Chef..",
		"Livreurs" => "Delivery Men",
		"Administrateurs" => "Admins",
		"Reclamations" => "Complains",
		"Produits" => "Products",
		"Categories" => "Categories",
		"Avis" => "Reviews",
		"Commandes" => "Orders",
		"Commentaires" => "Comments",


		"nom_chef" => "Chef name",
		"nom_recette" => "Recipe name",
		"type" => "Recipe type",
		"duree" => "Duration",
		"difficulte" => "Difficulty",
		"nbr_pers" => "Number of persons",
		"ingredients" => "Ingredients",
		"preparation" => "Prepration",
		"image_recette" => "Recipe Picture",
		"liste_recettes" => "List of Recipes",
		"ajouter_recette" => "Add a recipe",
		"modifier_recette" => "Recipe Update",
		"MsgSupp" => "Recipe deleted successfully",
		"RechercherPlaceholder" => "Name recipe.."

	);

?>